# Generated by Django 5.1.3 on 2024-11-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='reseña',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_reseñas/'),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
